dist: trusty
language: php
php:
  - 7.0
addons:
  sonarqube:
    organization: "tboronczyk-github"
    token:
      secure: "kKxy+Vfh3hRvmfPeIa+u0ulFeOb8euU9Q/e5YKURsn+qpZQqbRsFbAdaG61pdPIT+sBJ84YPai/uXgD7oE1WR8oB7nKmvsfOwG3s6by1zum0XjAHc1exu6K6lBHHemQbT4UHz9d/2NVj3nk2bIJMLfKpv352YWfPeq9uKJSxv+DgfqqA2iBeZzeovVo5m63d2oXXKRXSMSJtp/acKpH7qib1Z8KBxb5NH/q0bCCvJ7P5fqejEm8nmxMxTJOtR7K3m574+IuLaKf3lHfW4M5i70q08/6NuflOujL0DW8l+sfQa8YUiXkOEK5kED+LNGRNVVW3Gs9CHEXWDeSBm4MEXX2SDD/0fK5j/OrgCzGwF7c0N7RbfqO3U9cjC1AG48nK9MVLYyubXulgjJe93vf9kmoeTQzN4LmM1gx2PxB/klDlD3BP5v2tQHGlZVMgSGRcX7fNW7TGfI4PoWHuyQsA8CS7Jd5L6AxGEDlFH5zGJHjO36rfi+7DqNqnjeVmX1bzHIbguX3jj9WlmOKmiB4qZ4CUFfNm+1L+DE3L5mqNwp0vCM284boaV95vn0I/uoeZ7EZuJaxFQB4tvSMtPvQsgGfvM/zckKsOF3zIqAwGAcApRRljiCjwSgTTeR2mZpjzSkDmmCNn/6VBeikBdbyISQVUxEUPYf5W/LEvsgvr6mY="
before_script:
  - curl -O http://getcomposer.org/composer.phar
  - php composer.phar install --dev
script: 
  - vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=log.xml tests
  - sonar-scanner
after_success:
- bash <(curl -s https://codecov.io/bash)
